/**
 * This file was generated by the @pikku/cli
 */
/**
 * This provides the structure needed for typescript to be aware of RPCs and their return types
 */
    


// Custom types are those that are defined directly within generics
// or are broken into simpler types
export type SayHelloInput = { name?: string; }
export type PikkuFn_src_mcp_functions_ts_L12C3Output = { type: string; text: string; }[]
export type DisableToolInput = { name: string; }
export type PikkuFn_src_mcp_functions_ts_L25C3Output = { type: string; text: string; }[]
export type CalculateInput = { operation: "add" | "subtract" | "multiply" | "divide"; a: number; b: number; }
export type PikkuFn_src_mcp_functions_ts_L52C4Output = { type: string; text: string; }[]
export type PikkuFn_src_mcp_functions_ts_L88C55Output = { uri: any; text: string; }[]
export type GetUserInfoInput = { userId: string; }
export type PikkuFn_src_mcp_functions_ts_L101C3Output = { uri: string; text: string; }[]
export type PikkuFn_src_mcp_functions_ts_L140C66Output = { role: string; content: { type: string; text: string; }; }[]
export type DynamicPromptGeneratorInput = { topic: string; complexity: "beginner" | "intermediate" | "advanced"; includeExamples?: string; }
export type PikkuFn_src_mcp_functions_ts_L159C4Output = { role: "user"; content: { type: "text"; text: string; }; }[]

interface RPCHandler<I, O> {
    input: I;
    output: O;
}

export type RPCMap = {
  readonly 'sayHello': RPCHandler<SayHelloInput, PikkuFn_src_mcp_functions_ts_L12C3Output>,
  readonly 'disableTool': RPCHandler<DisableToolInput, PikkuFn_src_mcp_functions_ts_L25C3Output>,
  readonly 'calculate': RPCHandler<CalculateInput, PikkuFn_src_mcp_functions_ts_L52C4Output>,
  readonly 'getStaticResource': RPCHandler<null, PikkuFn_src_mcp_functions_ts_L88C55Output>,
  readonly 'getUserInfo': RPCHandler<GetUserInfoInput, PikkuFn_src_mcp_functions_ts_L101C3Output>,
  readonly 'staticPromptGenerator': RPCHandler<null, PikkuFn_src_mcp_functions_ts_L140C66Output>,
  readonly 'dynamicPromptGenerator': RPCHandler<DynamicPromptGeneratorInput, PikkuFn_src_mcp_functions_ts_L159C4Output>,
};


export type RPCInvoke = <Name extends keyof RPCMap>(
  name: Name,
  data: RPCMap[Name]['input'],
  options?: {
    location?: 'local' | 'remote' | 'auto'
  }
) => Promise<RPCMap[Name]['output']>

export type TypedPikkuRPC = {
  depth: number;
  global: boolean;
  invoke: RPCInvoke;
}
  