/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('rpc', 'meta', {
  "sayHello": {
    "pikkuFuncName": "pikkuFn_src_mcp_functions_ts_L12C3",
    "exposed": false
  },
  "disableTool": {
    "pikkuFuncName": "pikkuFn_src_mcp_functions_ts_L25C3",
    "exposed": false
  },
  "calculate": {
    "pikkuFuncName": "pikkuFn_src_mcp_functions_ts_L52C4",
    "exposed": false
  },
  "getStaticResource": {
    "pikkuFuncName": "pikkuFn_src_mcp_functions_ts_L88C55",
    "exposed": false
  },
  "getUserInfo": {
    "pikkuFuncName": "pikkuFn_src_mcp_functions_ts_L101C3",
    "exposed": false
  },
  "staticPromptGenerator": {
    "pikkuFuncName": "pikkuFn_src_mcp_functions_ts_L140C66",
    "exposed": false
  },
  "dynamicPromptGenerator": {
    "pikkuFuncName": "pikkuFn_src_mcp_functions_ts_L159C4",
    "exposed": false
  }
})