/**
 * This file was generated by @pikku/cli@0.12.15
 */
/**
 * This provides the structure needed for typescript to be aware of RPCs and their return types
 */





export type AgentApproveCallerInput = { agentName: string; runId: string; approvals: { toolCallId: string; approved: boolean; }[]; }
export type AgentCallerInput = { agentName: string; message: string; threadId: string; resourceId: string; }
export type AgentResumeCallerInput = { agentName: string; runId: string; toolCallId: string; approved: boolean; }
export type AgentStreamCallerInput = { agentName: string; message: string; threadId: string; resourceId: string; }
export type CompleteTodoInput = {
    /** Todo ID */
    id: string;
}
export type CompleteTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
    success: boolean;
}
export type CreateTodoInput = {
    title: string;
    description?: string | undefined;
    priority: ("low" | "medium" | "high") | undefined;
    dueDate?: string | undefined;
    tags: string[] | undefined;
    /** User ID (uses demo user if not provided) */
    userId?: (string | null) | undefined;
}
export type CreateTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    };
}
export type CreateTodoToolInput = {
    title: string;
    description?: string | undefined;
    priority: ("low" | "medium" | "high") | undefined;
    dueDate?: string | undefined;
    tags: string[] | undefined;
    /** User ID (uses demo user if not provided) */
    userId?: (string | null) | undefined;
}
export type CreateTodoToolOutput = { type: "text"; text: string; }[]
export type DeleteTodoInput = {
    /** Todo ID */
    id: string;
}
export type DeleteTodoOutput = {
    success: boolean;
}
export type GetTodoInput = {
    /** Todo ID */
    id: string;
}
export type GetTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
}
export type GetTodoResourceInput = { id: string; }
export type GetTodoResourceOutput = { uri: string; text: string; }[]
export type HttpOptionsRpcRpcNameInput = { rpcName: string; }
export type ListTodosInput = {
    completed?: boolean | undefined;
    priority?: ("low" | "medium" | "high") | undefined;
    tag?: string | undefined;
    /** User ID (uses demo user if not provided) */
    userId?: (string | null) | undefined;
}
export type ListTodosOutput = {
    todos: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    }[];
    total: number;
}
export type OnTestEventInput = {
    payload: string;
}
export type OnTestEventOutput = {
    payload: string;
}
export type PlanDayPromptInput = {
    /** User ID (uses demo user if not provided) */
    userId?: (string | null) | undefined;
}
export type PlanDayPromptOutput = { role: "user"; content: { type: "text"; text: string; }; }[]
export type PrioritizePromptInput = {
    /** User ID (uses demo user if not provided) */
    userId?: (string | null) | undefined;
    /** Prioritization focus */
    focus?: (("urgency" | "importance" | "quick-wins") | null) | undefined;
}
export type PrioritizePromptOutput = { role: "user"; content: { type: "text"; text: string; }; }[]
export type RpcCallerInput = { rpcName: string; data?: unknown; }
export type TestEventTriggerInput = { eventName: string; }
export type TestEventTriggerOutput = { payload: string; }
export type UpdateTodoInput = {
    /** Todo ID */
    id: string;
    title?: string | undefined;
    description?: string | undefined;
    priority?: ("low" | "medium" | "high") | undefined;
    dueDate?: string | undefined;
    tags?: string[] | undefined;
    completed?: boolean | undefined;
}
export type UpdateTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
    success: boolean;
}

interface RPCHandler<I, O> {
    input: I;
    output: O;
}

export type RPCMap = {
};



// No addon packages, use RPCMap directly
export type FlattenedRPCMap = RPCMap


export type RPCInvoke = <Name extends keyof FlattenedRPCMap>(
  name: Name,
  data: FlattenedRPCMap[Name]['input']
) => Promise<FlattenedRPCMap[Name]['output']>

export type RPCRemote = <Name extends keyof FlattenedRPCMap>(
  name: Name,
  data: FlattenedRPCMap[Name]['input']
) => Promise<FlattenedRPCMap[Name]['output']>

import type { WorkflowMap } from '../workflow/pikku-workflow-map.gen.d.js'

import type { AgentMap } from '../agent/pikku-agent-map.gen.d.js'


type FlattenedAgentMap = AgentMap


import type { PikkuRPC } from '@pikku/core/rpc'

interface AIAgentInput {
  message: string
  threadId: string
  resourceId: string
}

export type TypedStartWorkflow = <Name extends keyof WorkflowMap>(
  name: Name,
  input: WorkflowMap[Name]['input'],
  options?: { startNode?: string }
) => Promise<{ runId: string }>

type TypedAgentRun = [keyof FlattenedAgentMap] extends [never]
  ? (name: string, input: AIAgentInput) => Promise<any>
  : <Name extends keyof FlattenedAgentMap>(
      name: Name,
      input: AIAgentInput
    ) => Promise<{ runId: string; result: FlattenedAgentMap[Name]['output']; usage: { inputTokens: number; outputTokens: number } }>

type TypedAgentStream = [keyof FlattenedAgentMap] extends [never]
  ? (name: string, input: AIAgentInput, options?: { requiresToolApproval?: 'all' | 'explicit' | false }) => Promise<void>
  : <Name extends keyof FlattenedAgentMap>(
      name: Name,
      input: AIAgentInput,
      options?: { requiresToolApproval?: 'all' | 'explicit' | false }
    ) => Promise<void>

export type TypedPikkuRPC = PikkuRPC<RPCInvoke, RPCRemote, TypedStartWorkflow, TypedAgentRun, TypedAgentStream>
  