/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('mcp', 'resourcesMeta', {
  "getStaticResource": {
    "pikkuFuncName": "pikkuFn_src_mcp_functions_ts_L88C55",
    "uri": "getStaticResource",
    "title": "Static Resource",
    "description": "Gets a static resource with predefined data",
    "inputSchema": null,
    "outputSchema": "PikkuFn_src_mcp_functions_ts_L88C55Output"
  },
  "getUserInfo/{userId}": {
    "pikkuFuncName": "pikkuFn_src_mcp_functions_ts_L101C3",
    "uri": "getUserInfo/{userId}",
    "title": "User Information",
    "description": "Retrieve user information by user ID",
    "tags": [
      "user",
      "profile",
      "data"
    ],
    "inputSchema": "GetUserInfoInput",
    "outputSchema": "PikkuFn_src_mcp_functions_ts_L101C3Output"
  }
})
pikkuState('mcp', 'toolsMeta', {
  "sayHello": {
    "pikkuFuncName": "pikkuFn_src_mcp_functions_ts_L12C3",
    "name": "sayHello",
    "description": "Greet someone with a friendly hello message",
    "tags": [
      "greeting",
      "hello",
      "demo"
    ],
    "inputSchema": "SayHelloInput",
    "outputSchema": "PikkuFn_src_mcp_functions_ts_L12C3Output"
  },
  "disableTool": {
    "pikkuFuncName": "pikkuFn_src_mcp_functions_ts_L25C3",
    "name": "disableTool",
    "description": "Disable a tool by name",
    "inputSchema": "DisableToolInput",
    "outputSchema": "PikkuFn_src_mcp_functions_ts_L25C3Output"
  },
  "calculate": {
    "pikkuFuncName": "pikkuFn_src_mcp_functions_ts_L52C4",
    "name": "calculate",
    "description": "Perform basic mathematical operations (add, subtract, multiply, divide)",
    "tags": [
      "math",
      "calculator",
      "arithmetic"
    ],
    "inputSchema": "CalculateInput",
    "outputSchema": "PikkuFn_src_mcp_functions_ts_L52C4Output"
  }
})
pikkuState('mcp', 'promptsMeta', {
  "getStaticResource": {
    "pikkuFuncName": "pikkuFn_src_mcp_functions_ts_L140C66",
    "name": "getStaticResource",
    "description": "A static prompt that returns a predefined message",
    "inputSchema": null,
    "outputSchema": "PikkuFn_src_mcp_functions_ts_L140C66Output",
    "arguments": []
  },
  "dynamicPromptGenerator": {
    "pikkuFuncName": "pikkuFn_src_mcp_functions_ts_L159C4",
    "name": "dynamicPromptGenerator",
    "description": "Generate educational content with progressive complexity and optional examples",
    "tags": [
      "education",
      "content",
      "progressive",
      "examples"
    ],
    "inputSchema": "DynamicPromptGeneratorInput",
    "outputSchema": "PikkuFn_src_mcp_functions_ts_L159C4Output",
    "arguments": [
      {
        "name": "topic",
        "description": "topic parameter",
        "required": true
      },
      {
        "name": "complexity",
        "description": "complexity parameter",
        "required": true
      },
      {
        "name": "includeExamples",
        "description": "includeExamples parameter",
        "required": false
      }
    ]
  }
})