/**
 * This file was generated by @pikku/cli@0.11.2
 */
/**
 * This provides the structure needed for TypeScript to be aware of workflows and their input/output types
 */



// Custom types are those that are defined directly within generics
// or are broken into simpler types
export type SayHelloInput = { name?: string; }
export type SayHelloOutput = { type: string; text: string; }[]
export type DisableToolInput = { name: string; }
export type DisableToolOutput = { type: string; text: string; }[]
export type CalculateInput = { operation: "add" | "subtract" | "multiply" | "divide"; a: number; b: number; }
export type CalculateOutput = { type: string; text: string; }[]
export type GetStaticResourceOutput = { uri: any; text: string; }[]
export type GetUserInfoInput = { userId: string; }
export type GetUserInfoOutput = { uri: any; text: string; }[]
export type StaticPromptGeneratorOutput = { role: string; content: { type: string; text: string; }; }[]
export type DynamicPromptGeneratorInput = { topic: string; complexity: "beginner" | "intermediate" | "advanced"; includeExamples?: string; }
export type DynamicPromptGeneratorOutput = { role: "user"; content: { type: "text"; text: string; }; }[]

interface WorkflowHandler<I, O> {
    input: I;
    output: O;
}

export type WorkflowMap = {
};


/**
 * Type-safe workflow client API
 */
export type WorkflowClient<Name extends keyof WorkflowMap> = {
  /**
   * Start a new workflow run
   */
  start: (input: WorkflowMap[Name]['input']) => Promise<{ runId: string }>;

  /**
   * Get a workflow run by ID
   */
  getRun: <output extends keyof WorkflowMap[Name]>(runId: string) => Promise<WorkflowMap[Name][output]>;

  /**
   * Cancel a running workflow
   */
  cancelRun: (runId: string) => Promise<boolean>;
}

/**
 * Map of all registered workflows with type-safe client APIs
 */
export type TypedWorkflowClients = {
  [Name in keyof WorkflowMap]: WorkflowClient<Name>;
}
  