/**
 * This file was generated by @pikku/cli@0.11.3
 */
/**
 * This provides the structure needed for TypeScript to be aware of channels
 */



export type ListTodosInput = unknown
export type ListTodosOutput = unknown
export type GetTodoInput = unknown
export type GetTodoOutput = unknown
export type CreateTodoInput = unknown
export type CreateTodoOutput = unknown
export type UpdateTodoInput = unknown
export type UpdateTodoOutput = unknown
export type DeleteTodoInput = unknown
export type DeleteTodoOutput = unknown
export type CompleteTodoInput = unknown
export type CompleteTodoOutput = unknown
export type GetTodoResourceInput = { id: string; }
export type GetTodoResourceOutput = { uri: any; text: string; }[]
export type CreateTodoToolInput = { title: string; description?: string; priority?: "low" | "medium" | "high"; dueDate?: string; tags?: string[]; userId?: string; }
export type CreateTodoToolOutput = { type: string; text: string; }[]
export type CompleteTodoToolInput = { id: string; }
export type CompleteTodoToolOutput = { type: string; text: string; }[]
export type DeleteTodoToolInput = { id: string; }
export type DeleteTodoToolOutput = { type: string; text: string; }[]
export type PlanDayPromptInput = unknown
export type PlanDayPromptOutput = { role: "user"; content: { type: "text"; text: string; }; }[]
export type PrioritizePromptInput = unknown
export type PrioritizePromptOutput = { role: string; content: { type: string; text: string; }; }[]
export type GreetInput = { name: string; greeting?: string; }
export type GreetOutput = { message: string; timestamp: number; serverPort: number; }
export type RemoteGreetInput = { name: string; greeting?: string; }
export type RemoteGreetOutput = { message: string; timestamp: number; serverPort: number; }
export type TestEventTriggerInput = { eventName: string; }
export type TestEventTriggerOutput = { payload: string; }
export type OnTestEventInput = unknown
export type OnTestEventOutput = unknown
export type RpcCallerInput = { rpcName: string; data?: unknown; }
export type PikkuFn_src_wirings_rpc_wiring_ts_L31C9Input = { rpcName: string; }

interface ChannelHandler<I, O> {
    input: I;
    output: O;
}

export type ChannelsMap = {
};

export type ChannelDefaultHandlerOf<Channel extends keyof ChannelsMap> =
    ChannelsMap[Channel]['defaultMessage'] extends { input: infer I; output: infer O }
        ? ChannelHandler<I, O>
        : never;

export type ChannelWiringHandlerOf<
    Channel extends keyof ChannelsMap, 
    Route extends keyof ChannelsMap[Channel]['routes'], 
    Method extends keyof ChannelsMap[Channel]['routes'][Route],
> =
    ChannelsMap[Channel]['routes'][Route][Method] extends { input: infer I; output: infer O }
        ? ChannelHandler<I, O>
        : never;
