/**
 * This file was generated by @pikku/cli@0.11.2
 */
/**
 * This provides the structure needed for TypeScript to be aware of channels
 */
    


// Custom types are those that are defined directly within generics
// or are broken into simpler types
export type SayHelloInput = { name?: string; }
export type SayHelloOutput = { type: string; text: string; }[]
export type DisableToolInput = { name: string; }
export type DisableToolOutput = { type: string; text: string; }[]
export type CalculateInput = { operation: "add" | "subtract" | "multiply" | "divide"; a: number; b: number; }
export type CalculateOutput = { type: string; text: string; }[]
export type GetStaticResourceOutput = { uri: any; text: string; }[]
export type GetUserInfoInput = { userId: string; }
export type GetUserInfoOutput = { uri: any; text: string; }[]
export type StaticPromptGeneratorOutput = { role: string; content: { type: string; text: string; }; }[]
export type DynamicPromptGeneratorInput = { topic: string; complexity: "beginner" | "intermediate" | "advanced"; includeExamples?: string; }
export type DynamicPromptGeneratorOutput = { role: "user"; content: { type: "text"; text: string; }; }[]

interface ChannelHandler<I, O> {
    input: I;
    output: O;
}

export type ChannelsMap = {
};

export type ChannelDefaultHandlerOf<Channel extends keyof ChannelsMap> =
    ChannelsMap[Channel]['defaultMessage'] extends { input: infer I; output: infer O }
        ? ChannelHandler<I, O>
        : never;

export type ChannelWiringHandlerOf<
    Channel extends keyof ChannelsMap, 
    Route extends keyof ChannelsMap[Channel]['routes'], 
    Method extends keyof ChannelsMap[Channel]['routes'][Route],
> =
    ChannelsMap[Channel]['routes'][Route][Method] extends { input: infer I; output: infer O }
        ? ChannelHandler<I, O>
        : never;
