/**
 * This file was generated by the @pikku/cli
 */
import './mcp/pikku-mcp-wirings-meta.gen.js'
import './rpc/pikku-rpc-wirings-meta.gen.js'
import './function/pikku-functions-meta.gen.js'
import './function/pikku-functions.gen.js'
import './schemas/register.gen.js'
import './mcp/pikku-mcp-wirings.gen.js'