/**
 * This file was generated by @pikku/cli@0.11.2
 */
/**
 * This provides the structure needed for typescript to be aware of routes and their return types
 */
    


// Custom types are those that are defined directly within generics
// or are broken into simpler types
export type SayHelloInput = { name?: string; }
export type SayHelloOutput = { type: string; text: string; }[]
export type DisableToolInput = { name: string; }
export type DisableToolOutput = { type: string; text: string; }[]
export type CalculateInput = { operation: "add" | "subtract" | "multiply" | "divide"; a: number; b: number; }
export type CalculateOutput = { type: string; text: string; }[]
export type GetStaticResourceOutput = { uri: any; text: string; }[]
export type GetUserInfoInput = { userId: string; }
export type GetUserInfoOutput = { uri: any; text: string; }[]
export type StaticPromptGeneratorOutput = { role: string; content: { type: string; text: string; }; }[]
export type DynamicPromptGeneratorInput = { topic: string; complexity: "beginner" | "intermediate" | "advanced"; includeExamples?: string; }
export type DynamicPromptGeneratorOutput = { role: "user"; content: { type: "text"; text: string; }; }[]

// The '& {}' is a workaround for not directly refering to a type since it confuses typescript


interface HTTPWiringHandler<I, O> {
    input: I;
    output: O;
}

export type HTTPWiringsMap = {
};

export type HTTPWiringHandlerOf<HTTPWiring extends keyof HTTPWiringsMap, Method extends keyof HTTPWiringsMap[HTTPWiring]> =
    HTTPWiringsMap[HTTPWiring][Method] extends { input: infer I; output: infer O }
        ? HTTPWiringHandler<I, O>
        : never;

export type HTTPWiringsWithMethod<Method extends string> = {
  [HTTPWiring in keyof HTTPWiringsMap]: Method extends keyof HTTPWiringsMap[HTTPWiring] ? HTTPWiring : never;
}[keyof HTTPWiringsMap];
  