/**
 * This file was generated by @pikku/cli@0.11.3
 */
/**
 * This provides the structure needed for typescript to be aware of routes and their return types
 */



export type ListTodosInput = {
    completed?: boolean | undefined;
    priority?: ("low" | "medium" | "high") | undefined;
    tag?: string | undefined;
    /** User ID (uses demo user if not provided) */
    userId?: (string | null) | undefined;
}
export type ListTodosOutput = {
    todos: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    }[];
    total: number;
}
export type GetTodoInput = {
    /** Todo ID */
    id: string;
}
export type GetTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
}
export type CreateTodoInput = {
    title: string;
    description?: string | undefined;
    priority: ("low" | "medium" | "high") | undefined;
    dueDate?: string | undefined;
    tags: string[] | undefined;
    /** User ID (uses demo user if not provided) */
    userId?: (string | null) | undefined;
}
export type CreateTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    };
}
export type UpdateTodoInput = {
    /** Todo ID */
    id: string;
    title?: string | undefined;
    description?: string | undefined;
    priority?: ("low" | "medium" | "high") | undefined;
    dueDate?: string | undefined;
    tags?: string[] | undefined;
    completed?: boolean | undefined;
}
export type UpdateTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
    success: boolean;
}
export type DeleteTodoInput = {
    /** Todo ID */
    id: string;
}
export type DeleteTodoOutput = {
    success: boolean;
}
export type CompleteTodoInput = {
    /** Todo ID */
    id: string;
}
export type CompleteTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
    success: boolean;
}
export type GetTodoResourceInput = { id: string; }
export type GetTodoResourceOutput = { uri: any; text: string; }[]
export type CreateTodoToolInput = { title: string; description?: string; priority?: "low" | "medium" | "high"; dueDate?: string; tags?: string[]; userId?: string; }
export type CreateTodoToolOutput = { type: string; text: string; }[]
export type CompleteTodoToolInput = { id: string; }
export type CompleteTodoToolOutput = { type: string; text: string; }[]
export type DeleteTodoToolInput = { id: string; }
export type DeleteTodoToolOutput = { type: string; text: string; }[]
export type PlanDayPromptInput = {
    /** User ID (uses demo user if not provided) */
    userId?: (string | null) | undefined;
}
export type PlanDayPromptOutput = { role: "user"; content: { type: "text"; text: string; }; }[]
export type PrioritizePromptInput = {
    /** User ID (uses demo user if not provided) */
    userId?: (string | null) | undefined;
    /** Prioritization focus */
    focus?: (("urgency" | "importance" | "quick-wins") | null) | undefined;
}
export type PrioritizePromptOutput = { role: string; content: { type: string; text: string; }; }[]
export type GreetInput = { name: string; greeting?: string; }
export type GreetOutput = { message: string; timestamp: number; serverPort: number; }
export type RemoteGreetInput = { name: string; greeting?: string; }
export type RemoteGreetOutput = { message: string; timestamp: number; serverPort: number; }
export type TestEventTriggerInput = { eventName: string; }
export type TestEventTriggerOutput = { payload: string; }
export type OnTestEventInput = {
    payload: string;
}
export type OnTestEventOutput = {
    payload: string;
}
export type RpcCallerInput = { rpcName: string; data?: unknown; }
export type PikkuFn_src_wirings_rpc_wiring_ts_L31C9Input = { rpcName: string; }

// The '& {}' is a workaround for not directly refering to a type since it confuses typescript
export type GreetInputBody = GreetInput & {}
export type RemoteGreetInputBody = RemoteGreetInput & {}
export type RpcCallerInputParams = Pick<RpcCallerInput, 'rpcName'> & {}
export type RpcCallerInputBody = Omit<RpcCallerInput, 'rpcName'> & {}

interface HTTPWiringHandler<I, O> {
    input: I;
    output: O;
}

export type HTTPWiringsMap = {
  readonly '/workflow/review': {
    readonly POST: HTTPWiringHandler<null, null>,
  },
  readonly '/greet': {
    readonly POST: HTTPWiringHandler<GreetInput, GreetOutput>,
  },
  readonly '/remote-greet': {
    readonly POST: HTTPWiringHandler<RemoteGreetInput, RemoteGreetOutput>,
  },
  readonly '/rpc/:rpcName': {
    readonly POST: HTTPWiringHandler<RpcCallerInput, null>,
    readonly OPTIONS: HTTPWiringHandler<PikkuFn_src_wirings_rpc_wiring_ts_L31C9Input, null>,
  },
};

export type HTTPWiringHandlerOf<HTTPWiring extends keyof HTTPWiringsMap, Method extends keyof HTTPWiringsMap[HTTPWiring]> =
    HTTPWiringsMap[HTTPWiring][Method] extends { input: infer I; output: infer O }
        ? HTTPWiringHandler<I, O>
        : never;

export type HTTPWiringsWithMethod<Method extends string> = {
  [HTTPWiring in keyof HTTPWiringsMap]: Method extends keyof HTTPWiringsMap[HTTPWiring] ? HTTPWiring : never;
}[keyof HTTPWiringsMap];
  