/**
 * This file was generated by @pikku/cli@0.11.2
 */
/**
 * This provides the structure needed for typescript to be aware of Queue workers and their input/output types
 */
    


// Custom types are those that are defined directly within generics
// or are broken into simpler types
export type SayHelloInput = { name?: string; }
export type SayHelloOutput = { type: string; text: string; }[]
export type DisableToolInput = { name: string; }
export type DisableToolOutput = { type: string; text: string; }[]
export type CalculateInput = { operation: "add" | "subtract" | "multiply" | "divide"; a: number; b: number; }
export type CalculateOutput = { type: string; text: string; }[]
export type GetStaticResourceOutput = { uri: any; text: string; }[]
export type GetUserInfoInput = { userId: string; }
export type GetUserInfoOutput = { uri: any; text: string; }[]
export type StaticPromptGeneratorOutput = { role: string; content: { type: string; text: string; }; }[]
export type DynamicPromptGeneratorInput = { topic: string; complexity: "beginner" | "intermediate" | "advanced"; includeExamples?: string; }
export type DynamicPromptGeneratorOutput = { role: "user"; content: { type: "text"; text: string; }; }[]

import type { QueueJob } from '@pikku/core/queue'

interface QueueHandler<I, O> {
    input: I;
    output: O;
}

export type QueueMap = {
};


type QueueAdd = <Name extends keyof QueueMap>(
  name: Name,
  data: QueueMap[Name]['input'],
  options?: {
    priority?: number
    delay?: number
    attempts?: number
    removeOnComplete?: number
    removeOnFail?: number
    jobId?: string
  }
) => Promise<string>

type QueueGetJob = <Name extends keyof QueueMap>(
  name: Name,
  jobId: string
) => Promise<QueueJob<QueueMap[Name]['input'], QueueMap[Name]['output']> | null>

export type TypedPikkuQueue = {
  add: QueueAdd;
  getJob: QueueGetJob;
}
  