/**
 * This file was generated by @pikku/cli@0.11.3
 */
/**
 * This provides the structure needed for typescript to be aware of Queue workers and their input/output types
 */



export type GetTodoResourceInput = { id: string; }
export type GetTodoResourceOutput = { uri: any; text: string; }[]
export type CreateTodoToolInput = { title: string; description?: string; priority?: "low" | "medium" | "high"; dueDate?: string; tags?: string[]; userId?: string; }
export type CreateTodoToolOutput = { type: string; text: string; }[]
export type CompleteTodoToolInput = { id: string; }
export type CompleteTodoToolOutput = { type: string; text: string; }[]
export type DeleteTodoToolInput = { id: string; }
export type DeleteTodoToolOutput = { type: string; text: string; }[]
export type PlanDayPromptInput = unknown
export type PlanDayPromptOutput = { role: "user"; content: { type: "text"; text: string; }; }[]
export type PrioritizePromptInput = unknown
export type PrioritizePromptOutput = { role: string; content: { type: string; text: string; }; }[]
export type ListTodosInput = unknown
export type ListTodosOutput = unknown
export type GetTodoInput = unknown
export type GetTodoOutput = unknown
export type CreateTodoInput = unknown
export type CreateTodoOutput = unknown
export type UpdateTodoInput = unknown
export type UpdateTodoOutput = unknown
export type DeleteTodoInput = unknown
export type DeleteTodoOutput = unknown
export type CompleteTodoInput = unknown
export type CompleteTodoOutput = unknown
export type TestEventTriggerInput = { eventName: string; }
export type TestEventTriggerOutput = { payload: string; }
export type OnTestEventInput = unknown
export type OnTestEventOutput = unknown
export type RpcCallerInput = { rpcName: string; data?: unknown; }
export type PikkuFn_src_wirings_rpc_wiring_ts_L31C9Input = { rpcName: string; }

import type { QueueJob } from '@pikku/core/queue'

interface QueueHandler<I, O> {
    input: I;
    output: O;
}

export type QueueMap = {
};


type QueueAdd = <Name extends keyof QueueMap>(
  name: Name,
  data: QueueMap[Name]['input'],
  options?: {
    priority?: number
    delay?: number
    attempts?: number
    removeOnComplete?: number
    removeOnFail?: number
    jobId?: string
  }
) => Promise<string>

type QueueGetJob = <Name extends keyof QueueMap>(
  name: Name,
  jobId: string
) => Promise<QueueJob<QueueMap[Name]['input'], QueueMap[Name]['output']> | null>

export type TypedPikkuQueue = {
  add: QueueAdd;
  getJob: QueueGetJob;
}
  