/**
 * This file was generated by the @pikku/cli
 */
/* Import and register RPCs */
import { addFunction } from '@pikku/core'
import { calculate } from '../../src/mcp.functions.js'
import { disableTool } from '../../src/mcp.functions.js'
import { dynamicPromptGenerator } from '../../src/mcp.functions.js'
import { getStaticResource } from '../../src/mcp.functions.js'
import { getUserInfo } from '../../src/mcp.functions.js'
import { sayHello } from '../../src/mcp.functions.js'
import { staticPromptGenerator } from '../../src/mcp.functions.js'

addFunction('calculate', { func: calculate })
addFunction('disableTool', { func: disableTool })
addFunction('dynamicPromptGenerator', { func: dynamicPromptGenerator })
addFunction('getStaticResource', { func: getStaticResource })
addFunction('getUserInfo', { func: getUserInfo })
addFunction('sayHello', { func: sayHello })
addFunction('staticPromptGenerator', { func: staticPromptGenerator })