/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('function', 'meta', {
  "pikkuFn_src_mcp_functions_ts_L12C3": {
    "pikkuFuncName": "pikkuFn_src_mcp_functions_ts_L12C3",
    "name": "sayHello",
    "services": {
      "optimized": false,
      "services": []
    },
    "schemaName": "SayHelloInput",
    "inputs": [
      "SayHelloInput"
    ],
    "outputs": [
      "PikkuFn_src_mcp_functions_ts_L12C3Output"
    ]
  },
  "pikkuFn_src_mcp_functions_ts_L25C3": {
    "pikkuFuncName": "pikkuFn_src_mcp_functions_ts_L25C3",
    "name": "disableTool",
    "services": {
      "optimized": false,
      "services": []
    },
    "schemaName": "DisableToolInput",
    "inputs": [
      "DisableToolInput"
    ],
    "outputs": [
      "PikkuFn_src_mcp_functions_ts_L25C3Output"
    ]
  },
  "pikkuFn_src_mcp_functions_ts_L52C4": {
    "pikkuFuncName": "pikkuFn_src_mcp_functions_ts_L52C4",
    "name": "calculate",
    "services": {
      "optimized": true,
      "services": [
        "logger"
      ]
    },
    "schemaName": "CalculateInput",
    "inputs": [
      "CalculateInput"
    ],
    "outputs": [
      "PikkuFn_src_mcp_functions_ts_L52C4Output"
    ]
  },
  "pikkuFn_src_mcp_functions_ts_L88C55": {
    "pikkuFuncName": "pikkuFn_src_mcp_functions_ts_L88C55",
    "name": "getStaticResource",
    "services": {
      "optimized": true,
      "services": [
        "mcp"
      ]
    },
    "schemaName": null,
    "inputs": [],
    "outputs": [
      "PikkuFn_src_mcp_functions_ts_L88C55Output"
    ]
  },
  "pikkuFn_src_mcp_functions_ts_L101C3": {
    "pikkuFuncName": "pikkuFn_src_mcp_functions_ts_L101C3",
    "name": "getUserInfo",
    "services": {
      "optimized": false,
      "services": []
    },
    "schemaName": "GetUserInfoInput",
    "inputs": [
      "GetUserInfoInput"
    ],
    "outputs": [
      "PikkuFn_src_mcp_functions_ts_L101C3Output"
    ]
  },
  "pikkuFn_src_mcp_functions_ts_L140C66": {
    "pikkuFuncName": "pikkuFn_src_mcp_functions_ts_L140C66",
    "name": "staticPromptGenerator",
    "services": {
      "optimized": true,
      "services": []
    },
    "schemaName": null,
    "inputs": [],
    "outputs": [
      "PikkuFn_src_mcp_functions_ts_L140C66Output"
    ]
  },
  "pikkuFn_src_mcp_functions_ts_L159C4": {
    "pikkuFuncName": "pikkuFn_src_mcp_functions_ts_L159C4",
    "name": "dynamicPromptGenerator",
    "services": {
      "optimized": false,
      "services": []
    },
    "schemaName": "DynamicPromptGeneratorInput",
    "inputs": [
      "DynamicPromptGeneratorInput"
    ],
    "outputs": [
      "PikkuFn_src_mcp_functions_ts_L159C4Output"
    ]
  }
})