/**
 * This file was generated by @pikku/cli@0.11.3
 */
/* Import and register functions used by RPCs */
import { addFunction } from '@pikku/core'
import { completeTodo } from '../../src/functions/todos.functions.js'
import { createTodo } from '../../src/functions/todos.functions.js'
import { deleteTodo } from '../../src/functions/todos.functions.js'
import { getTodo } from '../../src/functions/todos.functions.js'
import { listTodos } from '../../src/functions/todos.functions.js'
import { onTestEvent } from '../../src/functions/trigger.functions.js'

addFunction('completeTodo', completeTodo)
addFunction('createTodo', createTodo)
addFunction('deleteTodo', deleteTodo)
addFunction('getTodo', getTodo)
addFunction('listTodos', listTodos)
addFunction('onTestEvent', onTestEvent)