/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('function', 'meta', {
  "sayHello": {
    "pikkuFuncName": "sayHello",
    "name": "sayHello",
    "services": {
      "optimized": false,
      "services": []
    },
    "inputSchemaName": "SayHelloInput",
    "outputSchemaName": "SayHelloOutput",
    "inputs": [
      "SayHelloInput"
    ],
    "outputs": [
      "SayHelloOutput"
    ],
    "isDirectFunction": true
  },
  "disableTool": {
    "pikkuFuncName": "disableTool",
    "name": "disableTool",
    "services": {
      "optimized": false,
      "services": []
    },
    "inputSchemaName": "DisableToolInput",
    "outputSchemaName": "DisableToolOutput",
    "inputs": [
      "DisableToolInput"
    ],
    "outputs": [
      "DisableToolOutput"
    ],
    "isDirectFunction": true
  },
  "calculate": {
    "pikkuFuncName": "calculate",
    "name": "calculate",
    "services": {
      "optimized": true,
      "services": [
        "logger"
      ]
    },
    "inputSchemaName": "CalculateInput",
    "outputSchemaName": "CalculateOutput",
    "inputs": [
      "CalculateInput"
    ],
    "outputs": [
      "CalculateOutput"
    ],
    "isDirectFunction": true
  },
  "getStaticResource": {
    "pikkuFuncName": "getStaticResource",
    "name": "getStaticResource",
    "services": {
      "optimized": true,
      "services": [
        "mcp"
      ]
    },
    "inputSchemaName": null,
    "outputSchemaName": "GetStaticResourceOutput",
    "inputs": [],
    "outputs": [
      "GetStaticResourceOutput"
    ],
    "isDirectFunction": true
  },
  "getUserInfo": {
    "pikkuFuncName": "getUserInfo",
    "name": "getUserInfo",
    "services": {
      "optimized": false,
      "services": []
    },
    "inputSchemaName": "GetUserInfoInput",
    "outputSchemaName": "GetUserInfoOutput",
    "inputs": [
      "GetUserInfoInput"
    ],
    "outputs": [
      "GetUserInfoOutput"
    ],
    "isDirectFunction": true
  },
  "staticPromptGenerator": {
    "pikkuFuncName": "staticPromptGenerator",
    "name": "staticPromptGenerator",
    "services": {
      "optimized": true,
      "services": []
    },
    "inputSchemaName": null,
    "outputSchemaName": "StaticPromptGeneratorOutput",
    "inputs": [],
    "outputs": [
      "StaticPromptGeneratorOutput"
    ],
    "isDirectFunction": true
  },
  "dynamicPromptGenerator": {
    "pikkuFuncName": "dynamicPromptGenerator",
    "name": "dynamicPromptGenerator",
    "services": {
      "optimized": false,
      "services": []
    },
    "inputSchemaName": "DynamicPromptGeneratorInput",
    "outputSchemaName": "DynamicPromptGeneratorOutput",
    "inputs": [
      "DynamicPromptGeneratorInput"
    ],
    "outputs": [
      "DynamicPromptGeneratorOutput"
    ],
    "isDirectFunction": true
  }
})