/**
 * This file was generated by the @pikku/cli
 */
import { addSchema } from '@pikku/core/schema'

import * as SayHelloInput from './schemas/SayHelloInput.schema.json' with { type: 'json' }
addSchema('SayHelloInput', SayHelloInput)


import * as PikkuFn_src_mcp_functions_ts_L12C3Output from './schemas/PikkuFn_src_mcp_functions_ts_L12C3Output.schema.json' with { type: 'json' }
addSchema('PikkuFn_src_mcp_functions_ts_L12C3Output', PikkuFn_src_mcp_functions_ts_L12C3Output)


import * as DisableToolInput from './schemas/DisableToolInput.schema.json' with { type: 'json' }
addSchema('DisableToolInput', DisableToolInput)


import * as PikkuFn_src_mcp_functions_ts_L25C3Output from './schemas/PikkuFn_src_mcp_functions_ts_L25C3Output.schema.json' with { type: 'json' }
addSchema('PikkuFn_src_mcp_functions_ts_L25C3Output', PikkuFn_src_mcp_functions_ts_L25C3Output)


import * as CalculateInput from './schemas/CalculateInput.schema.json' with { type: 'json' }
addSchema('CalculateInput', CalculateInput)


import * as PikkuFn_src_mcp_functions_ts_L52C4Output from './schemas/PikkuFn_src_mcp_functions_ts_L52C4Output.schema.json' with { type: 'json' }
addSchema('PikkuFn_src_mcp_functions_ts_L52C4Output', PikkuFn_src_mcp_functions_ts_L52C4Output)


import * as PikkuFn_src_mcp_functions_ts_L88C55Output from './schemas/PikkuFn_src_mcp_functions_ts_L88C55Output.schema.json' with { type: 'json' }
addSchema('PikkuFn_src_mcp_functions_ts_L88C55Output', PikkuFn_src_mcp_functions_ts_L88C55Output)


import * as GetUserInfoInput from './schemas/GetUserInfoInput.schema.json' with { type: 'json' }
addSchema('GetUserInfoInput', GetUserInfoInput)


import * as PikkuFn_src_mcp_functions_ts_L101C3Output from './schemas/PikkuFn_src_mcp_functions_ts_L101C3Output.schema.json' with { type: 'json' }
addSchema('PikkuFn_src_mcp_functions_ts_L101C3Output', PikkuFn_src_mcp_functions_ts_L101C3Output)


import * as PikkuFn_src_mcp_functions_ts_L140C66Output from './schemas/PikkuFn_src_mcp_functions_ts_L140C66Output.schema.json' with { type: 'json' }
addSchema('PikkuFn_src_mcp_functions_ts_L140C66Output', PikkuFn_src_mcp_functions_ts_L140C66Output)


import * as DynamicPromptGeneratorInput from './schemas/DynamicPromptGeneratorInput.schema.json' with { type: 'json' }
addSchema('DynamicPromptGeneratorInput', DynamicPromptGeneratorInput)


import * as PikkuFn_src_mcp_functions_ts_L159C4Output from './schemas/PikkuFn_src_mcp_functions_ts_L159C4Output.schema.json' with { type: 'json' }
addSchema('PikkuFn_src_mcp_functions_ts_L159C4Output', PikkuFn_src_mcp_functions_ts_L159C4Output)
